import type { IrregularVerb, RegularVerb, VerbEntry } from "@/lib/conjugation/de/types";

// ==== 弱変化動詞（規則動詞） ====
// 語幹と少数の音韻フラグだけで活用を機械的に導出できる動詞
const regularVerbs: RegularVerb[] = [
  { id: "machen", infinitive: "machen", meaning: "する、作る", kind: "regular", auxiliary: "haben" },
  { id: "sagen", infinitive: "sagen", meaning: "言う", kind: "regular", auxiliary: "haben" },
  { id: "spielen", infinitive: "spielen", meaning: "遊ぶ、演奏する", kind: "regular", auxiliary: "haben" },
  { id: "wohnen", infinitive: "wohnen", meaning: "住む", kind: "regular", auxiliary: "haben" },
  { id: "kaufen", infinitive: "kaufen", meaning: "買う", kind: "regular", auxiliary: "haben" },
  { id: "lernen", infinitive: "lernen", meaning: "学ぶ", kind: "regular", auxiliary: "haben" },
  { id: "hoeren", infinitive: "hören", meaning: "聞く", kind: "regular", auxiliary: "haben" },
  { id: "kochen", infinitive: "kochen", meaning: "料理する", kind: "regular", auxiliary: "haben" },
  { id: "lieben", infinitive: "lieben", meaning: "愛する", kind: "regular", auxiliary: "haben" },
  { id: "brauchen", infinitive: "brauchen", meaning: "必要とする", kind: "regular", auxiliary: "haben" },
  {
    id: "arbeiten",
    infinitive: "arbeiten",
    meaning: "働く",
    kind: "regular",
    auxiliary: "haben",
    linkingE: true,
  },
  {
    id: "oeffnen",
    infinitive: "öffnen",
    meaning: "開ける",
    kind: "regular",
    auxiliary: "haben",
    linkingE: true,
  },
  {
    id: "warten",
    infinitive: "warten",
    meaning: "待つ",
    kind: "regular",
    auxiliary: "haben",
    linkingE: true,
  },
  {
    id: "reisen",
    infinitive: "reisen",
    meaning: "旅行する",
    kind: "regular",
    auxiliary: "sein",
    sibilantStem: true,
  },
  {
    id: "tanzen",
    infinitive: "tanzen",
    meaning: "踊る",
    kind: "regular",
    auxiliary: "haben",
    sibilantStem: true,
  },
  {
    id: "studieren",
    infinitive: "studieren",
    meaning: "(大学で)勉強する",
    kind: "regular",
    auxiliary: "haben",
    noGePrefix: true,
  },
  {
    id: "besuchen",
    infinitive: "besuchen",
    meaning: "訪れる",
    kind: "regular",
    auxiliary: "haben",
    noGePrefix: true,
  },
  {
    id: "verkaufen",
    infinitive: "verkaufen",
    meaning: "売る",
    kind: "regular",
    auxiliary: "haben",
    noGePrefix: true,
  },
  {
    id: "erzaehlen",
    infinitive: "erzählen",
    meaning: "語る、話す",
    kind: "regular",
    auxiliary: "haben",
    noGePrefix: true,
  },
];

// ==== 強変化動詞・混合変化動詞（不規則動詞） ====
// 現在人称変化・過去基本形・過去分詞・接続法II式の語幹を明示的に指定する
const irregularVerbs: IrregularVerb[] = [
  {
    id: "sein",
    infinitive: "sein",
    meaning: "〜である、いる",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["bin", "bist", "ist", "sind", "seid", "sind"],
    präteritum: ["war", "warst", "war", "waren", "wart", "waren"],
    partizipII: "gewesen",
    konjunktivIIBase: "wär",
    konjunktivIOverride: ["sei", "seist", "sei", "seien", "seiet", "seien"],
  },
  {
    id: "haben",
    infinitive: "haben",
    meaning: "持っている",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["habe", "hast", "hat", "haben", "habt", "haben"],
    präteritum: ["hatte", "hattest", "hatte", "hatten", "hattet", "hatten"],
    partizipII: "gehabt",
    konjunktivIIBase: "hätt",
  },
  {
    id: "werden",
    infinitive: "werden",
    meaning: "〜になる",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["werde", "wirst", "wird", "werden", "werdet", "werden"],
    präteritum: ["wurde", "wurdest", "wurde", "wurden", "wurdet", "wurden"],
    partizipII: "geworden",
    konjunktivIIBase: "würd",
  },
  {
    id: "koennen",
    infinitive: "können",
    meaning: "〜できる",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["kann", "kannst", "kann", "können", "könnt", "können"],
    präteritum: ["konnte", "konntest", "konnte", "konnten", "konntet", "konnten"],
    partizipII: "gekonnt",
    konjunktivIIBase: "könnt",
  },
  {
    id: "muessen",
    infinitive: "müssen",
    meaning: "〜しなければならない",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["muss", "musst", "muss", "müssen", "müsst", "müssen"],
    präteritum: ["musste", "musstest", "musste", "mussten", "musstet", "mussten"],
    partizipII: "gemusst",
    konjunktivIIBase: "müsst",
  },
  {
    id: "wollen",
    infinitive: "wollen",
    meaning: "〜したい",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["will", "willst", "will", "wollen", "wollt", "wollen"],
    präteritum: ["wollte", "wolltest", "wollte", "wollten", "wolltet", "wollten"],
    partizipII: "gewollt",
    konjunktivIIBase: "wollt",
  },
  {
    id: "sollen",
    infinitive: "sollen",
    meaning: "〜すべきだ",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["soll", "sollst", "soll", "sollen", "sollt", "sollen"],
    präteritum: ["sollte", "solltest", "sollte", "sollten", "solltet", "sollten"],
    partizipII: "gesollt",
    konjunktivIIBase: "sollt",
  },
  {
    id: "duerfen",
    infinitive: "dürfen",
    meaning: "〜してもよい",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["darf", "darfst", "darf", "dürfen", "dürft", "dürfen"],
    präteritum: ["durfte", "durftest", "durfte", "durften", "durftet", "durften"],
    partizipII: "gedurft",
    konjunktivIIBase: "dürft",
  },
  {
    id: "moegen",
    infinitive: "mögen",
    meaning: "好む",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["mag", "magst", "mag", "mögen", "mögt", "mögen"],
    präteritum: ["mochte", "mochtest", "mochte", "mochten", "mochtet", "mochten"],
    partizipII: "gemocht",
    konjunktivIIBase: "möcht",
  },
  {
    id: "wissen",
    infinitive: "wissen",
    meaning: "知っている(事柄)",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["weiß", "weißt", "weiß", "wissen", "wisst", "wissen"],
    präteritum: ["wusste", "wusstest", "wusste", "wussten", "wusstet", "wussten"],
    partizipII: "gewusst",
    konjunktivIIBase: "wüsst",
  },
  {
    id: "gehen",
    infinitive: "gehen",
    meaning: "行く",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["gehe", "gehst", "geht", "gehen", "geht", "gehen"],
    präteritum: ["ging", "gingst", "ging", "gingen", "gingt", "gingen"],
    partizipII: "gegangen",
    konjunktivIIBase: "ging",
  },
  {
    id: "kommen",
    infinitive: "kommen",
    meaning: "来る",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["komme", "kommst", "kommt", "kommen", "kommt", "kommen"],
    präteritum: ["kam", "kamst", "kam", "kamen", "kamt", "kamen"],
    partizipII: "gekommen",
    konjunktivIIBase: "käm",
  },
  {
    id: "fahren",
    infinitive: "fahren",
    meaning: "(乗り物で)行く",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["fahre", "fährst", "fährt", "fahren", "fahrt", "fahren"],
    präteritum: ["fuhr", "fuhrst", "fuhr", "fuhren", "fuhrt", "fuhren"],
    partizipII: "gefahren",
    konjunktivIIBase: "führ",
  },
  {
    id: "laufen",
    infinitive: "laufen",
    meaning: "走る、歩く",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["laufe", "läufst", "läuft", "laufen", "lauft", "laufen"],
    präteritum: ["lief", "liefst", "lief", "liefen", "lieft", "liefen"],
    partizipII: "gelaufen",
    konjunktivIIBase: "lief",
  },
  {
    id: "fliegen",
    infinitive: "fliegen",
    meaning: "飛ぶ",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["fliege", "fliegst", "fliegt", "fliegen", "fliegt", "fliegen"],
    präteritum: ["flog", "flogst", "flog", "flogen", "flogt", "flogen"],
    partizipII: "geflogen",
    konjunktivIIBase: "flög",
  },
  {
    id: "schwimmen",
    infinitive: "schwimmen",
    meaning: "泳ぐ",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["schwimme", "schwimmst", "schwimmt", "schwimmen", "schwimmt", "schwimmen"],
    präteritum: ["schwamm", "schwammst", "schwamm", "schwammen", "schwammt", "schwammen"],
    partizipII: "geschwommen",
    konjunktivIIBase: "schwömm",
  },
  {
    id: "sehen",
    infinitive: "sehen",
    meaning: "見る",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["sehe", "siehst", "sieht", "sehen", "seht", "sehen"],
    präteritum: ["sah", "sahst", "sah", "sahen", "saht", "sahen"],
    partizipII: "gesehen",
    konjunktivIIBase: "säh",
  },
  {
    id: "geben",
    infinitive: "geben",
    meaning: "与える",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["gebe", "gibst", "gibt", "geben", "gebt", "geben"],
    präteritum: ["gab", "gabst", "gab", "gaben", "gabt", "gaben"],
    partizipII: "gegeben",
    konjunktivIIBase: "gäb",
  },
  {
    id: "nehmen",
    infinitive: "nehmen",
    meaning: "取る",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["nehme", "nimmst", "nimmt", "nehmen", "nehmt", "nehmen"],
    präteritum: ["nahm", "nahmst", "nahm", "nahmen", "nahmt", "nahmen"],
    partizipII: "genommen",
    konjunktivIIBase: "nähm",
  },
  {
    id: "sprechen",
    infinitive: "sprechen",
    meaning: "話す",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["spreche", "sprichst", "spricht", "sprechen", "sprecht", "sprechen"],
    präteritum: ["sprach", "sprachst", "sprach", "sprachen", "spracht", "sprachen"],
    partizipII: "gesprochen",
    konjunktivIIBase: "spräch",
  },
  {
    id: "essen",
    infinitive: "essen",
    meaning: "食べる",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["esse", "isst", "isst", "essen", "esst", "essen"],
    präteritum: ["aß", "aßt", "aß", "aßen", "aßt", "aßen"],
    partizipII: "gegessen",
    konjunktivIIBase: "äß",
  },
  {
    id: "lesen",
    infinitive: "lesen",
    meaning: "読む",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["lese", "liest", "liest", "lesen", "lest", "lesen"],
    präteritum: ["las", "last", "las", "lasen", "last", "lasen"],
    partizipII: "gelesen",
    konjunktivIIBase: "läs",
  },
  {
    id: "schreiben",
    infinitive: "schreiben",
    meaning: "書く",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["schreibe", "schreibst", "schreibt", "schreiben", "schreibt", "schreiben"],
    präteritum: ["schrieb", "schriebst", "schrieb", "schrieben", "schriebt", "schrieben"],
    partizipII: "geschrieben",
    konjunktivIIBase: "schrieb",
  },
  {
    id: "bleiben",
    infinitive: "bleiben",
    meaning: "とどまる",
    kind: "irregular",
    auxiliary: "sein",
    präsens: ["bleibe", "bleibst", "bleibt", "bleiben", "bleibt", "bleiben"],
    präteritum: ["blieb", "bliebst", "blieb", "blieben", "bliebt", "blieben"],
    partizipII: "geblieben",
    konjunktivIIBase: "blieb",
  },
  {
    id: "trinken",
    infinitive: "trinken",
    meaning: "飲む",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["trinke", "trinkst", "trinkt", "trinken", "trinkt", "trinken"],
    präteritum: ["trank", "trankst", "trank", "tranken", "trankt", "tranken"],
    partizipII: "getrunken",
    konjunktivIIBase: "tränk",
  },
  {
    id: "singen",
    infinitive: "singen",
    meaning: "歌う",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["singe", "singst", "singt", "singen", "singt", "singen"],
    präteritum: ["sang", "sangst", "sang", "sangen", "sangt", "sangen"],
    partizipII: "gesungen",
    konjunktivIIBase: "säng",
  },
  {
    id: "finden",
    infinitive: "finden",
    meaning: "見つける",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["finde", "findest", "findet", "finden", "findet", "finden"],
    präteritum: ["fand", "fandest", "fand", "fanden", "fandet", "fanden"],
    partizipII: "gefunden",
    konjunktivIIBase: "fänd",
  },
  {
    id: "helfen",
    infinitive: "helfen",
    meaning: "手伝う",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["helfe", "hilfst", "hilft", "helfen", "helft", "helfen"],
    präteritum: ["half", "halfst", "half", "halfen", "halft", "halfen"],
    partizipII: "geholfen",
    konjunktivIIBase: "hülf",
  },
  {
    id: "tragen",
    infinitive: "tragen",
    meaning: "運ぶ、着る",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["trage", "trägst", "trägt", "tragen", "tragt", "tragen"],
    präteritum: ["trug", "trugst", "trug", "trugen", "trugt", "trugen"],
    partizipII: "getragen",
    konjunktivIIBase: "trüg",
  },
  {
    id: "schlafen",
    infinitive: "schlafen",
    meaning: "眠る",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["schlafe", "schläfst", "schläft", "schlafen", "schlaft", "schlafen"],
    präteritum: ["schlief", "schliefst", "schlief", "schliefen", "schlieft", "schliefen"],
    partizipII: "geschlafen",
    konjunktivIIBase: "schlief",
  },
  {
    id: "waschen",
    infinitive: "waschen",
    meaning: "洗う",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["wasche", "wäschst", "wäscht", "waschen", "wascht", "waschen"],
    präteritum: ["wusch", "wuschst", "wusch", "wuschen", "wuscht", "wuschen"],
    partizipII: "gewaschen",
    konjunktivIIBase: "wüsch",
  },
  {
    id: "stehen",
    infinitive: "stehen",
    meaning: "立つ",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["stehe", "stehst", "steht", "stehen", "steht", "stehen"],
    präteritum: ["stand", "standest", "stand", "standen", "standet", "standen"],
    partizipII: "gestanden",
    konjunktivIIBase: "stünd",
  },
  {
    id: "verstehen",
    infinitive: "verstehen",
    meaning: "理解する",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["verstehe", "verstehst", "versteht", "verstehen", "versteht", "verstehen"],
    präteritum: ["verstand", "verstandest", "verstand", "verstanden", "verstandet", "verstanden"],
    partizipII: "verstanden",
    konjunktivIIBase: "verstünd",
  },
  {
    id: "denken",
    infinitive: "denken",
    meaning: "考える",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["denke", "denkst", "denkt", "denken", "denkt", "denken"],
    präteritum: ["dachte", "dachtest", "dachte", "dachten", "dachtet", "dachten"],
    partizipII: "gedacht",
    konjunktivIIBase: "dächt",
  },
  {
    id: "bringen",
    infinitive: "bringen",
    meaning: "持ってくる",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["bringe", "bringst", "bringt", "bringen", "bringt", "bringen"],
    präteritum: ["brachte", "brachtest", "brachte", "brachten", "brachtet", "brachten"],
    partizipII: "gebracht",
    konjunktivIIBase: "brächt",
  },
  {
    id: "kennen",
    infinitive: "kennen",
    meaning: "知っている(人・物)",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["kenne", "kennst", "kennt", "kennen", "kennt", "kennen"],
    präteritum: ["kannte", "kanntest", "kannte", "kannten", "kanntet", "kannten"],
    partizipII: "gekannt",
    konjunktivIIBase: "kennt",
  },
  {
    id: "nennen",
    infinitive: "nennen",
    meaning: "名づける",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["nenne", "nennst", "nennt", "nennen", "nennt", "nennen"],
    präteritum: ["nannte", "nanntest", "nannte", "nannten", "nanntet", "nannten"],
    partizipII: "genannt",
    konjunktivIIBase: "nennt",
  },
  {
    id: "schneiden",
    infinitive: "schneiden",
    meaning: "切る",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["schneide", "schneidest", "schneidet", "schneiden", "schneidet", "schneiden"],
    präteritum: ["schnitt", "schnittest", "schnitt", "schnitten", "schnittet", "schnitten"],
    partizipII: "geschnitten",
    konjunktivIIBase: "schnitt",
  },
  {
    id: "treffen",
    infinitive: "treffen",
    meaning: "会う",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["treffe", "triffst", "trifft", "treffen", "trefft", "treffen"],
    präteritum: ["traf", "trafst", "traf", "trafen", "traft", "trafen"],
    partizipII: "getroffen",
    konjunktivIIBase: "träf",
  },
  {
    id: "schliessen",
    infinitive: "schließen",
    meaning: "閉める",
    kind: "irregular",
    auxiliary: "haben",
    präsens: ["schließe", "schließt", "schließt", "schließen", "schließt", "schließen"],
    präteritum: ["schloss", "schlosst", "schloss", "schlossen", "schlosst", "schlossen"],
    partizipII: "geschlossen",
    konjunktivIIBase: "schlöss",
  },
];

export const verbs: VerbEntry[] = [...irregularVerbs, ...regularVerbs];
