import type { Auxiliary, IrregularVerb, SixForms, VerbEntry } from "@/lib/conjugation/fr/types";

// ==== 派生ヘルパー ====
// フランス語の不規則動詞には、語幹や語尾のパターンを共有する「動詞ファミリー」が多い。
// 手入力のミスを避けるため、そうしたファミリーはベース動詞や共通パターンから機械的に導出する。

// 接頭辞を付けるだけで活用が作れる動詞（revenir=re+venir, apprendre=ap+prendre など）
function prefixed(
  base: IrregularVerb,
  prefix: string,
  id: string,
  infinitive: string,
  meaning: string,
  overrides: Partial<{ auxiliary: Auxiliary; futurStem: string }> = {},
): IrregularVerb {
  const p6 = (arr: SixForms): SixForms => arr.map((f) => prefix + f) as SixForms;
  return {
    id,
    infinitive,
    meaning,
    kind: "irregular",
    auxiliary: overrides.auxiliary ?? base.auxiliary,
    pastParticiple: prefix + base.pastParticiple,
    présent: p6(base.présent),
    subjonctifPrésent: p6(base.subjonctifPrésent),
    passéSimple: p6(base.passéSimple),
    futurStem: overrides.futurStem ?? prefix + base.futurStem,
    ...(base.imparfaitStem ? { imparfaitStem: prefix + base.imparfaitStem } : {}),
  };
}

// -crire型(écrire, décrire, inscrire, prescrire, souscrire, transcrire)
// stemは「〜cri」で終わる語幹（例: "écri", "décri", "inscri"）を渡す
function crireVerb(stem: string, id: string, infinitive: string, meaning: string): IrregularVerb {
  const longStem = stem + "v";
  return {
    id,
    infinitive,
    meaning,
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: stem + "t",
    présent: [
      stem + "s",
      stem + "s",
      stem + "t",
      longStem + "ons",
      longStem + "ez",
      longStem + "ent",
    ],
    subjonctifPrésent: [
      longStem + "e",
      longStem + "es",
      longStem + "e",
      longStem + "ions",
      longStem + "iez",
      longStem + "ent",
    ],
    passéSimple: [
      longStem + "is",
      longStem + "is",
      longStem + "it",
      longStem + "îmes",
      longStem + "îtes",
      longStem + "irent",
    ],
    futurStem: stem + "r",
  };
}

// -uire型(conduire, produire, traduire, construire, détruire, réduire)
// stemは「〜du/stru」などで終わる語幹（例: "condu", "constru"）を渡す
function uireVerb(stem: string, id: string, infinitive: string, meaning: string): IrregularVerb {
  return {
    id,
    infinitive,
    meaning,
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: stem + "it",
    présent: [stem + "is", stem + "is", stem + "it", stem + "isons", stem + "isez", stem + "isent"],
    subjonctifPrésent: [
      stem + "ise",
      stem + "ises",
      stem + "ise",
      stem + "isions",
      stem + "isiez",
      stem + "isent",
    ],
    passéSimple: [
      stem + "isis",
      stem + "isis",
      stem + "isit",
      stem + "isîmes",
      stem + "isîtes",
      stem + "isirent",
    ],
    futurStem: stem + "ir",
  };
}

// ==== 不規則動詞: 派生のベースとなる基本形 ====
const etre: IrregularVerb = {
  id: "etre",
  infinitive: "être",
  meaning: "〜である、いる",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "été",
  présent: ["suis", "es", "est", "sommes", "êtes", "sont"],
  subjonctifPrésent: ["sois", "sois", "soit", "soyons", "soyez", "soient"],
  passéSimple: ["fus", "fus", "fut", "fûmes", "fûtes", "furent"],
  futurStem: "ser",
  imparfaitStem: "ét",
};

const avoir: IrregularVerb = {
  id: "avoir",
  infinitive: "avoir",
  meaning: "持っている",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "eu",
  présent: ["ai", "as", "a", "avons", "avez", "ont"],
  subjonctifPrésent: ["aie", "aies", "ait", "ayons", "ayez", "aient"],
  passéSimple: ["eus", "eus", "eut", "eûmes", "eûtes", "eurent"],
  futurStem: "aur",
};

const aller: IrregularVerb = {
  id: "aller",
  infinitive: "aller",
  meaning: "行く",
  kind: "irregular",
  auxiliary: "être",
  pastParticiple: "allé",
  présent: ["vais", "vas", "va", "allons", "allez", "vont"],
  subjonctifPrésent: ["aille", "ailles", "aille", "allions", "alliez", "aillent"],
  passéSimple: ["allai", "allas", "alla", "allâmes", "allâtes", "allèrent"],
  futurStem: "ir",
};

const faire: IrregularVerb = {
  id: "faire",
  infinitive: "faire",
  meaning: "する、作る",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "fait",
  présent: ["fais", "fais", "fait", "faisons", "faites", "font"],
  subjonctifPrésent: ["fasse", "fasses", "fasse", "fassions", "fassiez", "fassent"],
  passéSimple: ["fis", "fis", "fit", "fîmes", "fîtes", "firent"],
  futurStem: "fer",
};

const pouvoir: IrregularVerb = {
  id: "pouvoir",
  infinitive: "pouvoir",
  meaning: "〜できる",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "pu",
  présent: ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"],
  subjonctifPrésent: ["puisse", "puisses", "puisse", "puissions", "puissiez", "puissent"],
  passéSimple: ["pus", "pus", "put", "pûmes", "pûtes", "purent"],
  futurStem: "pourr",
};

const vouloir: IrregularVerb = {
  id: "vouloir",
  infinitive: "vouloir",
  meaning: "〜したい、欲しい",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "voulu",
  présent: ["veux", "veux", "veut", "voulons", "voulez", "veulent"],
  subjonctifPrésent: ["veuille", "veuilles", "veuille", "voulions", "vouliez", "veuillent"],
  passéSimple: ["voulus", "voulus", "voulut", "voulûmes", "voulûtes", "voulurent"],
  futurStem: "voudr",
};

const devoir: IrregularVerb = {
  id: "devoir",
  infinitive: "devoir",
  meaning: "〜しなければならない",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "dû",
  présent: ["dois", "dois", "doit", "devons", "devez", "doivent"],
  subjonctifPrésent: ["doive", "doives", "doive", "devions", "deviez", "doivent"],
  passéSimple: ["dus", "dus", "dut", "dûmes", "dûtes", "durent"],
  futurStem: "devr",
};

const savoir: IrregularVerb = {
  id: "savoir",
  infinitive: "savoir",
  meaning: "知っている",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "su",
  présent: ["sais", "sais", "sait", "savons", "savez", "savent"],
  subjonctifPrésent: ["sache", "saches", "sache", "sachions", "sachiez", "sachent"],
  passéSimple: ["sus", "sus", "sut", "sûmes", "sûtes", "surent"],
  futurStem: "saur",
};

const voir: IrregularVerb = {
  id: "voir",
  infinitive: "voir",
  meaning: "見る",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "vu",
  présent: ["vois", "vois", "voit", "voyons", "voyez", "voient"],
  subjonctifPrésent: ["voie", "voies", "voie", "voyions", "voyiez", "voient"],
  passéSimple: ["vis", "vis", "vit", "vîmes", "vîtes", "virent"],
  futurStem: "verr",
};

const prendre: IrregularVerb = {
  id: "prendre",
  infinitive: "prendre",
  meaning: "取る、乗る",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "pris",
  présent: ["prends", "prends", "prend", "prenons", "prenez", "prennent"],
  subjonctifPrésent: ["prenne", "prennes", "prenne", "prenions", "preniez", "prennent"],
  passéSimple: ["pris", "pris", "prit", "prîmes", "prîtes", "prirent"],
  futurStem: "prendr",
};

const venir: IrregularVerb = {
  id: "venir",
  infinitive: "venir",
  meaning: "来る",
  kind: "irregular",
  auxiliary: "être",
  pastParticiple: "venu",
  présent: ["viens", "viens", "vient", "venons", "venez", "viennent"],
  subjonctifPrésent: ["vienne", "viennes", "vienne", "venions", "veniez", "viennent"],
  passéSimple: ["vins", "vins", "vint", "vînmes", "vîntes", "vinrent"],
  futurStem: "viendr",
};

const tenir: IrregularVerb = {
  id: "tenir",
  infinitive: "tenir",
  meaning: "持つ、保つ",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "tenu",
  présent: ["tiens", "tiens", "tient", "tenons", "tenez", "tiennent"],
  subjonctifPrésent: ["tienne", "tiennes", "tienne", "tenions", "teniez", "tiennent"],
  passéSimple: ["tins", "tins", "tint", "tînmes", "tîntes", "tinrent"],
  futurStem: "tiendr",
};

const dire: IrregularVerb = {
  id: "dire",
  infinitive: "dire",
  meaning: "言う",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "dit",
  présent: ["dis", "dis", "dit", "disons", "dites", "disent"],
  subjonctifPrésent: ["dise", "dises", "dise", "disions", "disiez", "disent"],
  passéSimple: ["dis", "dis", "dit", "dîmes", "dîtes", "dirent"],
  futurStem: "dir",
};

const mettre: IrregularVerb = {
  id: "mettre",
  infinitive: "mettre",
  meaning: "置く、着る",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "mis",
  présent: ["mets", "mets", "met", "mettons", "mettez", "mettent"],
  subjonctifPrésent: ["mette", "mettes", "mette", "mettions", "mettiez", "mettent"],
  passéSimple: ["mis", "mis", "mit", "mîmes", "mîtes", "mirent"],
  futurStem: "mettr",
};

const partir: IrregularVerb = {
  id: "partir",
  infinitive: "partir",
  meaning: "出発する",
  kind: "irregular",
  auxiliary: "être",
  pastParticiple: "parti",
  présent: ["pars", "pars", "part", "partons", "partez", "partent"],
  subjonctifPrésent: ["parte", "partes", "parte", "partions", "partiez", "partent"],
  passéSimple: ["partis", "partis", "partit", "partîmes", "partîtes", "partirent"],
  futurStem: "partir",
};

const sortir: IrregularVerb = {
  id: "sortir",
  infinitive: "sortir",
  meaning: "出る、外出する",
  kind: "irregular",
  auxiliary: "être",
  pastParticiple: "sorti",
  présent: ["sors", "sors", "sort", "sortons", "sortez", "sortent"],
  subjonctifPrésent: ["sorte", "sortes", "sorte", "sortions", "sortiez", "sortent"],
  passéSimple: ["sortis", "sortis", "sortit", "sortîmes", "sortîtes", "sortirent"],
  futurStem: "sortir",
};

const connaitre: IrregularVerb = {
  id: "connaitre",
  infinitive: "connaître",
  meaning: "知っている（人・場所）",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "connu",
  présent: ["connais", "connais", "connaît", "connaissons", "connaissez", "connaissent"],
  subjonctifPrésent: [
    "connaisse",
    "connaisses",
    "connaisse",
    "connaissions",
    "connaissiez",
    "connaissent",
  ],
  passéSimple: ["connus", "connus", "connut", "connûmes", "connûtes", "connurent"],
  futurStem: "connaîtr",
};

const naitre: IrregularVerb = {
  id: "naitre",
  infinitive: "naître",
  meaning: "生まれる",
  kind: "irregular",
  auxiliary: "être",
  pastParticiple: "né",
  présent: ["nais", "nais", "naît", "naissons", "naissez", "naissent"],
  subjonctifPrésent: ["naisse", "naisses", "naisse", "naissions", "naissiez", "naissent"],
  passéSimple: ["naquis", "naquis", "naquit", "naquîmes", "naquîtes", "naquirent"],
  futurStem: "naîtr",
};

const joindre: IrregularVerb = {
  id: "joindre",
  infinitive: "joindre",
  meaning: "つなぐ、連絡する",
  kind: "irregular",
  auxiliary: "avoir",
  pastParticiple: "joint",
  présent: ["joins", "joins", "joint", "joignons", "joignez", "joignent"],
  subjonctifPrésent: ["joigne", "joignes", "joigne", "joignions", "joigniez", "joignent"],
  passéSimple: ["joignis", "joignis", "joignit", "joignîmes", "joignîtes", "joignirent"],
  futurStem: "joindr",
};

// これらは他の動詞ファミリーの派生元にはならない、単独の不規則動詞
const otherBaseIrregularVerbs: IrregularVerb[] = [
  {
    id: "valoir",
    infinitive: "valoir",
    meaning: "価値がある",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "valu",
    présent: ["vaux", "vaux", "vaut", "valons", "valez", "valent"],
    subjonctifPrésent: ["vaille", "vailles", "vaille", "valions", "valiez", "vaillent"],
    passéSimple: ["valus", "valus", "valut", "valûmes", "valûtes", "valurent"],
    futurStem: "vaudr",
  },
  {
    id: "recevoir",
    infinitive: "recevoir",
    meaning: "受け取る",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "reçu",
    présent: ["reçois", "reçois", "reçoit", "recevons", "recevez", "reçoivent"],
    subjonctifPrésent: ["reçoive", "reçoives", "reçoive", "recevions", "receviez", "reçoivent"],
    passéSimple: ["reçus", "reçus", "reçut", "reçûmes", "reçûtes", "reçurent"],
    futurStem: "recevr",
  },
  {
    id: "courir",
    infinitive: "courir",
    meaning: "走る",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "couru",
    présent: ["cours", "cours", "court", "courons", "courez", "courent"],
    subjonctifPrésent: ["coure", "coures", "coure", "courions", "couriez", "courent"],
    passéSimple: ["courus", "courus", "courut", "courûmes", "courûtes", "coururent"],
    futurStem: "courr",
  },
  {
    id: "mourir",
    infinitive: "mourir",
    meaning: "死ぬ",
    kind: "irregular",
    auxiliary: "être",
    pastParticiple: "mort",
    présent: ["meurs", "meurs", "meurt", "mourons", "mourez", "meurent"],
    subjonctifPrésent: ["meure", "meures", "meure", "mourions", "mouriez", "meurent"],
    passéSimple: ["mourus", "mourus", "mourut", "mourûmes", "mourûtes", "moururent"],
    futurStem: "mourr",
  },
  {
    id: "fuir",
    infinitive: "fuir",
    meaning: "逃げる",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "fui",
    présent: ["fuis", "fuis", "fuit", "fuyons", "fuyez", "fuient"],
    subjonctifPrésent: ["fuie", "fuies", "fuie", "fuyions", "fuyiez", "fuient"],
    passéSimple: ["fuis", "fuis", "fuit", "fuîmes", "fuîtes", "fuirent"],
    futurStem: "fuir",
  },
  {
    id: "dormir",
    infinitive: "dormir",
    meaning: "眠る",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "dormi",
    présent: ["dors", "dors", "dort", "dormons", "dormez", "dorment"],
    subjonctifPrésent: ["dorme", "dormes", "dorme", "dormions", "dormiez", "dorment"],
    passéSimple: ["dormis", "dormis", "dormit", "dormîmes", "dormîtes", "dormirent"],
    futurStem: "dormir",
  },
  {
    id: "servir",
    infinitive: "servir",
    meaning: "仕える、役立つ",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "servi",
    présent: ["sers", "sers", "sert", "servons", "servez", "servent"],
    subjonctifPrésent: ["serve", "serves", "serve", "servions", "serviez", "servent"],
    passéSimple: ["servis", "servis", "servit", "servîmes", "servîtes", "servirent"],
    futurStem: "servir",
  },
  {
    id: "mentir",
    infinitive: "mentir",
    meaning: "嘘をつく",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "menti",
    présent: ["mens", "mens", "ment", "mentons", "mentez", "mentent"],
    subjonctifPrésent: ["mente", "mentes", "mente", "mentions", "mentiez", "mentent"],
    passéSimple: ["mentis", "mentis", "mentit", "mentîmes", "mentîtes", "mentirent"],
    futurStem: "mentir",
  },
  {
    id: "acquerir",
    infinitive: "acquérir",
    meaning: "獲得する",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "acquis",
    présent: ["acquiers", "acquiers", "acquiert", "acquérons", "acquérez", "acquièrent"],
    subjonctifPrésent: [
      "acquière",
      "acquières",
      "acquière",
      "acquérions",
      "acquériez",
      "acquièrent",
    ],
    passéSimple: ["acquis", "acquis", "acquit", "acquîmes", "acquîtes", "acquirent"],
    futurStem: "acquerr",
  },
  {
    id: "ouvrir",
    infinitive: "ouvrir",
    meaning: "開ける",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "ouvert",
    présent: ["ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"],
    subjonctifPrésent: ["ouvre", "ouvres", "ouvre", "ouvrions", "ouvriez", "ouvrent"],
    passéSimple: ["ouvris", "ouvris", "ouvrit", "ouvrîmes", "ouvrîtes", "ouvrirent"],
    futurStem: "ouvrir",
  },
  {
    id: "offrir",
    infinitive: "offrir",
    meaning: "贈る、提供する",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "offert",
    présent: ["offre", "offres", "offre", "offrons", "offrez", "offrent"],
    subjonctifPrésent: ["offre", "offres", "offre", "offrions", "offriez", "offrent"],
    passéSimple: ["offris", "offris", "offrit", "offrîmes", "offrîtes", "offrirent"],
    futurStem: "offrir",
  },
  {
    id: "souffrir",
    infinitive: "souffrir",
    meaning: "苦しむ",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "souffert",
    présent: ["souffre", "souffres", "souffre", "souffrons", "souffrez", "souffrent"],
    subjonctifPrésent: ["souffre", "souffres", "souffre", "souffrions", "souffriez", "souffrent"],
    passéSimple: ["souffris", "souffris", "souffrit", "souffrîmes", "souffrîtes", "souffrirent"],
    futurStem: "souffrir",
  },
  {
    id: "croire",
    infinitive: "croire",
    meaning: "信じる、思う",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "cru",
    présent: ["crois", "crois", "croit", "croyons", "croyez", "croient"],
    subjonctifPrésent: ["croie", "croies", "croie", "croyions", "croyiez", "croient"],
    passéSimple: ["crus", "crus", "crut", "crûmes", "crûtes", "crurent"],
    futurStem: "croir",
  },
  {
    id: "boire",
    infinitive: "boire",
    meaning: "飲む",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "bu",
    présent: ["bois", "bois", "boit", "buvons", "buvez", "boivent"],
    subjonctifPrésent: ["boive", "boives", "boive", "buvions", "buviez", "boivent"],
    passéSimple: ["bus", "bus", "but", "bûmes", "bûtes", "burent"],
    futurStem: "boir",
  },
  {
    id: "lire",
    infinitive: "lire",
    meaning: "読む",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "lu",
    présent: ["lis", "lis", "lit", "lisons", "lisez", "lisent"],
    subjonctifPrésent: ["lise", "lises", "lise", "lisions", "lisiez", "lisent"],
    passéSimple: ["lus", "lus", "lut", "lûmes", "lûtes", "lurent"],
    futurStem: "lir",
  },
  {
    id: "vivre",
    infinitive: "vivre",
    meaning: "生きる",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "vécu",
    présent: ["vis", "vis", "vit", "vivons", "vivez", "vivent"],
    subjonctifPrésent: ["vive", "vives", "vive", "vivions", "viviez", "vivent"],
    passéSimple: ["vécus", "vécus", "vécut", "vécûmes", "vécûtes", "vécurent"],
    futurStem: "vivr",
  },
  {
    id: "suivre",
    infinitive: "suivre",
    meaning: "ついていく、受講する",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "suivi",
    présent: ["suis", "suis", "suit", "suivons", "suivez", "suivent"],
    subjonctifPrésent: ["suive", "suives", "suive", "suivions", "suiviez", "suivent"],
    passéSimple: ["suivis", "suivis", "suivit", "suivîmes", "suivîtes", "suivirent"],
    futurStem: "suivr",
  },
  {
    id: "plaire",
    infinitive: "plaire",
    meaning: "気に入る",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "plu",
    présent: ["plais", "plais", "plaît", "plaisons", "plaisez", "plaisent"],
    subjonctifPrésent: ["plaise", "plaises", "plaise", "plaisions", "plaisiez", "plaisent"],
    passéSimple: ["plus", "plus", "plut", "plûmes", "plûtes", "plurent"],
    futurStem: "plair",
  },
  {
    id: "rire",
    infinitive: "rire",
    meaning: "笑う",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "ri",
    présent: ["ris", "ris", "rit", "rions", "riez", "rient"],
    subjonctifPrésent: ["rie", "ries", "rie", "riions", "riiez", "rient"],
    passéSimple: ["ris", "ris", "rit", "rîmes", "rîtes", "rirent"],
    futurStem: "rir",
  },
  {
    id: "conclure",
    infinitive: "conclure",
    meaning: "結論づける",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "conclu",
    présent: ["conclus", "conclus", "conclut", "concluons", "concluez", "concluent"],
    subjonctifPrésent: ["conclue", "conclues", "conclue", "concluions", "concluiez", "concluent"],
    passéSimple: ["conclus", "conclus", "conclut", "conclûmes", "conclûtes", "conclurent"],
    futurStem: "conclur",
  },
  {
    id: "battre",
    infinitive: "battre",
    meaning: "打つ、負かす",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "battu",
    présent: ["bats", "bats", "bat", "battons", "battez", "battent"],
    subjonctifPrésent: ["batte", "battes", "batte", "battions", "battiez", "battent"],
    passéSimple: ["battis", "battis", "battit", "battîmes", "battîtes", "battirent"],
    futurStem: "battr",
  },
  {
    id: "vaincre",
    infinitive: "vaincre",
    meaning: "打ち負かす",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "vaincu",
    présent: ["vaincs", "vaincs", "vainc", "vainquons", "vainquez", "vainquent"],
    subjonctifPrésent: ["vainque", "vainques", "vainque", "vainquions", "vainquiez", "vainquent"],
    passéSimple: ["vainquis", "vainquis", "vainquit", "vainquîmes", "vainquîtes", "vainquirent"],
    futurStem: "vaincr",
  },
  {
    id: "craindre",
    infinitive: "craindre",
    meaning: "恐れる",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "craint",
    présent: ["crains", "crains", "craint", "craignons", "craignez", "craignent"],
    subjonctifPrésent: ["craigne", "craignes", "craigne", "craignions", "craigniez", "craignent"],
    passéSimple: ["craignis", "craignis", "craignit", "craignîmes", "craignîtes", "craignirent"],
    futurStem: "craindr",
  },
  {
    id: "peindre",
    infinitive: "peindre",
    meaning: "描く、塗る",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "peint",
    présent: ["peins", "peins", "peint", "peignons", "peignez", "peignent"],
    subjonctifPrésent: ["peigne", "peignes", "peigne", "peignions", "peigniez", "peignent"],
    passéSimple: ["peignis", "peignis", "peignit", "peignîmes", "peignîtes", "peignirent"],
    futurStem: "peindr",
  },
  {
    id: "plaindre",
    infinitive: "plaindre",
    meaning: "気の毒に思う",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "plaint",
    présent: ["plains", "plains", "plaint", "plaignons", "plaignez", "plaignent"],
    subjonctifPrésent: ["plaigne", "plaignes", "plaigne", "plaignions", "plaigniez", "plaignent"],
    passéSimple: ["plaignis", "plaignis", "plaignit", "plaignîmes", "plaignîtes", "plaignirent"],
    futurStem: "plaindr",
  },
  {
    id: "resoudre",
    infinitive: "résoudre",
    meaning: "解決する",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "résolu",
    présent: ["résous", "résous", "résout", "résolvons", "résolvez", "résolvent"],
    subjonctifPrésent: ["résolve", "résolves", "résolve", "résolvions", "résolviez", "résolvent"],
    passéSimple: ["résolus", "résolus", "résolut", "résolûmes", "résolûtes", "résolurent"],
    futurStem: "résoudr",
  },
  {
    id: "coudre",
    infinitive: "coudre",
    meaning: "縫う",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "cousu",
    présent: ["couds", "couds", "coud", "cousons", "cousez", "cousent"],
    subjonctifPrésent: ["couse", "couses", "couse", "cousions", "cousiez", "cousent"],
    passéSimple: ["cousis", "cousis", "cousit", "cousîmes", "cousîtes", "cousirent"],
    futurStem: "coudr",
  },
  {
    id: "appeler",
    infinitive: "appeler",
    meaning: "呼ぶ、電話する",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "appelé",
    présent: ["appelle", "appelles", "appelle", "appelons", "appelez", "appellent"],
    subjonctifPrésent: ["appelle", "appelles", "appelle", "appelions", "appeliez", "appellent"],
    passéSimple: ["appelai", "appelas", "appela", "appelâmes", "appelâtes", "appelèrent"],
    futurStem: "appeller",
  },
  {
    id: "acheter",
    infinitive: "acheter",
    meaning: "買う",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "acheté",
    présent: ["achète", "achètes", "achète", "achetons", "achetez", "achètent"],
    subjonctifPrésent: ["achète", "achètes", "achète", "achetions", "achetiez", "achètent"],
    passéSimple: ["achetai", "achetas", "acheta", "achetâmes", "achetâtes", "achetèrent"],
    futurStem: "achèter",
  },
  {
    id: "preferer",
    infinitive: "préférer",
    meaning: "〜の方を好む",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "préféré",
    présent: ["préfère", "préfères", "préfère", "préférons", "préférez", "préfèrent"],
    subjonctifPrésent: ["préfère", "préfères", "préfère", "préférions", "préfériez", "préfèrent"],
    passéSimple: ["préférai", "préféras", "préféra", "préférâmes", "préférâtes", "préférèrent"],
    futurStem: "préférer",
  },
  {
    id: "envoyer",
    infinitive: "envoyer",
    meaning: "送る",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "envoyé",
    présent: ["envoie", "envoies", "envoie", "envoyons", "envoyez", "envoient"],
    subjonctifPrésent: ["envoie", "envoies", "envoie", "envoyions", "envoyiez", "envoient"],
    passéSimple: ["envoyai", "envoyas", "envoya", "envoyâmes", "envoyâtes", "envoyèrent"],
    futurStem: "enverr",
  },
  {
    id: "employer",
    infinitive: "employer",
    meaning: "使う、雇う",
    kind: "irregular",
    auxiliary: "avoir",
    pastParticiple: "employé",
    présent: ["emploie", "emploies", "emploie", "employons", "employez", "emploient"],
    subjonctifPrésent: ["emploie", "emploies", "emploie", "employions", "employiez", "emploient"],
    passéSimple: ["employai", "employas", "employa", "employâmes", "employâtes", "employèrent"],
    futurStem: "emploier",
  },
];

// ==== -crire型・-uire型のファミリー ====
const crireFamily: IrregularVerb[] = [
  crireVerb("écri", "ecrire", "écrire", "書く"),
  crireVerb("décri", "decrire", "décrire", "描写する"),
  crireVerb("inscri", "inscrire", "inscrire", "登録する、記入する"),
  crireVerb("prescri", "prescrire", "prescrire", "処方する"),
  crireVerb("souscri", "souscrire", "souscrire", "加入する、署名する"),
  crireVerb("transcri", "transcrire", "transcrire", "書き写す"),
];

const uireFamily: IrregularVerb[] = [
  uireVerb("condu", "conduire", "conduire", "運転する"),
  uireVerb("produ", "produire", "produire", "生産する"),
  uireVerb("tradu", "traduire", "traduire", "翻訳する"),
  uireVerb("constru", "construire", "construire", "建てる"),
  uireVerb("détru", "detruire", "détruire", "破壊する"),
  uireVerb("rédu", "reduire", "réduire", "減らす"),
];

// ==== 接頭辞による派生動詞 ====
const prefixedFamily: IrregularVerb[] = [
  prefixed(venir, "re", "revenir", "revenir", "戻ってくる"),
  prefixed(venir, "de", "devenir", "devenir", "〜になる"),
  prefixed(venir, "pré", "prevenir", "prévenir", "警告する、予防する", { auxiliary: "avoir" }),

  prefixed(tenir, "re", "retenir", "retenir", "引き止める、覚えておく"),
  prefixed(tenir, "ob", "obtenir", "obtenir", "得る"),
  prefixed(tenir, "sou", "soutenir", "soutenir", "支える"),
  prefixed(tenir, "con", "contenir", "contenir", "含む"),
  prefixed(tenir, "appar", "appartenir", "appartenir", "〜に属する"),
  prefixed(tenir, "entre", "entretenir", "entretenir", "維持する"),

  prefixed(prendre, "ap", "apprendre", "apprendre", "学ぶ"),
  prefixed(prendre, "com", "comprendre", "comprendre", "理解する"),
  prefixed(prendre, "sur", "surprendre", "surprendre", "驚かせる"),
  prefixed(prendre, "re", "reprendre", "reprendre", "取り戻す、再開する"),

  prefixed(mettre, "per", "permettre", "permettre", "許可する"),
  prefixed(mettre, "pro", "promettre", "promettre", "約束する"),
  prefixed(mettre, "re", "remettre", "remettre", "戻す、延期する"),
  prefixed(mettre, "sou", "soumettre", "soumettre", "従わせる、提出する"),
  prefixed(mettre, "ad", "admettre", "admettre", "認める"),

  prefixed(voir, "re", "revoir", "revoir", "再び会う"),
  prefixed(voir, "pré", "prevoir", "prévoir", "予測する", { futurStem: "prévoir" }),

  prefixed(dire, "re", "redire", "redire", "繰り返して言う"),

  prefixed(connaitre, "re", "reconnaitre", "reconnaître", "認識する"),

  prefixed(naitre, "re", "renaitre", "renaître", "生まれ変わる"),

  prefixed(joindre, "re", "rejoindre", "rejoindre", "合流する"),
];

const irregularVerbs: VerbEntry[] = [
  etre,
  avoir,
  aller,
  faire,
  pouvoir,
  vouloir,
  devoir,
  savoir,
  voir,
  prendre,
  venir,
  tenir,
  dire,
  mettre,
  partir,
  sortir,
  connaitre,
  naitre,
  joindre,
  ...otherBaseIrregularVerbs,
  ...crireFamily,
  ...uireFamily,
  ...prefixedFamily,
];

// 規則動詞: 語尾変化のルールだけで活用可能なため、原形とグループのみ保持する
const regularVerbs: VerbEntry[] = [
  {
    id: "parler",
    infinitive: "parler",
    meaning: "話す",
    kind: "regular",
    group: 1,
    auxiliary: "avoir",
  },
  {
    id: "aimer",
    infinitive: "aimer",
    meaning: "好きである、愛する",
    kind: "regular",
    group: 1,
    auxiliary: "avoir",
  },
  {
    id: "chanter",
    infinitive: "chanter",
    meaning: "歌う",
    kind: "regular",
    group: 1,
    auxiliary: "avoir",
  },
  {
    id: "finir",
    infinitive: "finir",
    meaning: "終える",
    kind: "regular",
    group: 2,
    auxiliary: "avoir",
  },
  {
    id: "choisir",
    infinitive: "choisir",
    meaning: "選ぶ",
    kind: "regular",
    group: 2,
    auxiliary: "avoir",
  },
  {
    id: "reussir",
    infinitive: "réussir",
    meaning: "成功する",
    kind: "regular",
    group: 2,
    auxiliary: "avoir",
  },
  {
    id: "vendre",
    infinitive: "vendre",
    meaning: "売る",
    kind: "regular",
    group: 3,
    auxiliary: "avoir",
  },
  {
    id: "attendre",
    infinitive: "attendre",
    meaning: "待つ",
    kind: "regular",
    group: 3,
    auxiliary: "avoir",
  },
  {
    id: "repondre",
    infinitive: "répondre",
    meaning: "答える",
    kind: "regular",
    group: 3,
    auxiliary: "avoir",
  },
];

export const verbs: VerbEntry[] = [...irregularVerbs, ...regularVerbs];
