import type { IrregularVerb, VerbEntry } from "@/lib/conjugation/es/types";

// ==== 不規則動詞 ====
// 直説法現在・点過去・接続法現在は、規則変化のルールでは導けないため全形を直接指定する。
// 直説法線過去はser・ir・verの3つを除き、不定詞から規則的に導出されるため指定不要。
const irregularVerbs: IrregularVerb[] = [
  {
    id: "ser",
    infinitive: "ser",
    meaning: "〜である",
    kind: "irregular",
    participio: "sido",
    presente: ["soy", "eres", "es", "somos", "sois", "son"],
    pretéritoIndefinido: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
    subjuntivoPresente: ["sea", "seas", "sea", "seamos", "seáis", "sean"],
    futuroStem: "ser",
    pretéritoImperfecto: ["era", "eras", "era", "éramos", "erais", "eran"],
  },
  {
    id: "estar",
    infinitive: "estar",
    meaning: "（状態・場所に）ある、いる",
    kind: "irregular",
    participio: "estado",
    presente: ["estoy", "estás", "está", "estamos", "estáis", "están"],
    pretéritoIndefinido: ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"],
    subjuntivoPresente: ["esté", "estés", "esté", "estemos", "estéis", "estén"],
    futuroStem: "estar",
  },
  {
    id: "tener",
    infinitive: "tener",
    meaning: "持っている",
    kind: "irregular",
    participio: "tenido",
    presente: ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"],
    pretéritoIndefinido: ["tuve", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"],
    subjuntivoPresente: ["tenga", "tengas", "tenga", "tengamos", "tengáis", "tengan"],
    futuroStem: "tendr",
  },
  {
    id: "hacer",
    infinitive: "hacer",
    meaning: "する、作る",
    kind: "irregular",
    participio: "hecho",
    presente: ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
    pretéritoIndefinido: ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"],
    subjuntivoPresente: ["haga", "hagas", "haga", "hagamos", "hagáis", "hagan"],
    futuroStem: "har",
  },
  {
    id: "ir",
    infinitive: "ir",
    meaning: "行く",
    kind: "irregular",
    participio: "ido",
    presente: ["voy", "vas", "va", "vamos", "vais", "van"],
    pretéritoIndefinido: ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
    subjuntivoPresente: ["vaya", "vayas", "vaya", "vayamos", "vayáis", "vayan"],
    futuroStem: "ir",
    pretéritoImperfecto: ["iba", "ibas", "iba", "íbamos", "ibais", "iban"],
  },
  {
    id: "poder",
    infinitive: "poder",
    meaning: "〜できる",
    kind: "irregular",
    participio: "podido",
    presente: ["puedo", "puedes", "puede", "podemos", "podéis", "pueden"],
    pretéritoIndefinido: ["pude", "pudiste", "pudo", "pudimos", "pudisteis", "pudieron"],
    subjuntivoPresente: ["pueda", "puedas", "pueda", "podamos", "podáis", "puedan"],
    futuroStem: "podr",
  },
  {
    id: "saber",
    infinitive: "saber",
    meaning: "知っている",
    kind: "irregular",
    participio: "sabido",
    presente: ["sé", "sabes", "sabe", "sabemos", "sabéis", "saben"],
    pretéritoIndefinido: ["supe", "supiste", "supo", "supimos", "supisteis", "supieron"],
    subjuntivoPresente: ["sepa", "sepas", "sepa", "sepamos", "sepáis", "sepan"],
    futuroStem: "sabr",
  },
  {
    id: "querer",
    infinitive: "querer",
    meaning: "〜したい、愛する",
    kind: "irregular",
    participio: "querido",
    presente: ["quiero", "quieres", "quiere", "queremos", "queréis", "quieren"],
    pretéritoIndefinido: ["quise", "quisiste", "quiso", "quisimos", "quisisteis", "quisieron"],
    subjuntivoPresente: ["quiera", "quieras", "quiera", "queramos", "queráis", "quieran"],
    futuroStem: "querr",
  },
  {
    id: "poner",
    infinitive: "poner",
    meaning: "置く",
    kind: "irregular",
    participio: "puesto",
    presente: ["pongo", "pones", "pone", "ponemos", "ponéis", "ponen"],
    pretéritoIndefinido: ["puse", "pusiste", "puso", "pusimos", "pusisteis", "pusieron"],
    subjuntivoPresente: ["ponga", "pongas", "ponga", "pongamos", "pongáis", "pongan"],
    futuroStem: "pondr",
  },
  {
    id: "salir",
    infinitive: "salir",
    meaning: "出る、外出する",
    kind: "irregular",
    participio: "salido",
    presente: ["salgo", "sales", "sale", "salimos", "salís", "salen"],
    pretéritoIndefinido: ["salí", "saliste", "salió", "salimos", "salisteis", "salieron"],
    subjuntivoPresente: ["salga", "salgas", "salga", "salgamos", "salgáis", "salgan"],
    futuroStem: "saldr",
  },
  {
    id: "venir",
    infinitive: "venir",
    meaning: "来る",
    kind: "irregular",
    participio: "venido",
    presente: ["vengo", "vienes", "viene", "venimos", "venís", "vienen"],
    pretéritoIndefinido: ["vine", "viniste", "vino", "vinimos", "vinisteis", "vinieron"],
    subjuntivoPresente: ["venga", "vengas", "venga", "vengamos", "vengáis", "vengan"],
    futuroStem: "vendr",
  },
  {
    id: "decir",
    infinitive: "decir",
    meaning: "言う",
    kind: "irregular",
    participio: "dicho",
    presente: ["digo", "dices", "dice", "decimos", "decís", "dicen"],
    pretéritoIndefinido: ["dije", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"],
    subjuntivoPresente: ["diga", "digas", "diga", "digamos", "digáis", "digan"],
    futuroStem: "dir",
  },
  {
    id: "dar",
    infinitive: "dar",
    meaning: "与える",
    kind: "irregular",
    participio: "dado",
    presente: ["doy", "das", "da", "damos", "dais", "dan"],
    pretéritoIndefinido: ["di", "diste", "dio", "dimos", "disteis", "dieron"],
    subjuntivoPresente: ["dé", "des", "dé", "demos", "deis", "den"],
    futuroStem: "dar",
  },
  {
    id: "ver",
    infinitive: "ver",
    meaning: "見る",
    kind: "irregular",
    participio: "visto",
    presente: ["veo", "ves", "ve", "vemos", "veis", "ven"],
    pretéritoIndefinido: ["vi", "viste", "vio", "vimos", "visteis", "vieron"],
    subjuntivoPresente: ["vea", "veas", "vea", "veamos", "veáis", "vean"],
    futuroStem: "ver",
    pretéritoImperfecto: ["veía", "veías", "veía", "veíamos", "veíais", "veían"],
  },
  {
    id: "traer",
    infinitive: "traer",
    meaning: "持ってくる",
    kind: "irregular",
    participio: "traído",
    presente: ["traigo", "traes", "trae", "traemos", "traéis", "traen"],
    pretéritoIndefinido: ["traje", "trajiste", "trajo", "trajimos", "trajisteis", "trajeron"],
    subjuntivoPresente: ["traiga", "traigas", "traiga", "traigamos", "traigáis", "traigan"],
    futuroStem: "traer",
  },
  {
    id: "oir",
    infinitive: "oír",
    meaning: "聞こえる",
    kind: "irregular",
    participio: "oído",
    presente: ["oigo", "oyes", "oye", "oímos", "oís", "oyen"],
    pretéritoIndefinido: ["oí", "oíste", "oyó", "oímos", "oísteis", "oyeron"],
    subjuntivoPresente: ["oiga", "oigas", "oiga", "oigamos", "oigáis", "oigan"],
    futuroStem: "oír",
  },
  {
    id: "conocer",
    infinitive: "conocer",
    meaning: "知っている（人・場所）",
    kind: "irregular",
    participio: "conocido",
    presente: ["conozco", "conoces", "conoce", "conocemos", "conocéis", "conocen"],
    pretéritoIndefinido: ["conocí", "conociste", "conoció", "conocimos", "conocisteis", "conocieron"],
    subjuntivoPresente: ["conozca", "conozcas", "conozca", "conozcamos", "conozcáis", "conozcan"],
    futuroStem: "conocer",
  },
  {
    id: "pensar",
    infinitive: "pensar",
    meaning: "考える",
    kind: "irregular",
    participio: "pensado",
    presente: ["pienso", "piensas", "piensa", "pensamos", "pensáis", "piensan"],
    pretéritoIndefinido: ["pensé", "pensaste", "pensó", "pensamos", "pensasteis", "pensaron"],
    subjuntivoPresente: ["piense", "pienses", "piense", "pensemos", "penséis", "piensen"],
    futuroStem: "pensar",
  },
  {
    id: "volver",
    infinitive: "volver",
    meaning: "戻る",
    kind: "irregular",
    participio: "vuelto",
    presente: ["vuelvo", "vuelves", "vuelve", "volvemos", "volvéis", "vuelven"],
    pretéritoIndefinido: ["volví", "volviste", "volvió", "volvimos", "volvisteis", "volvieron"],
    subjuntivoPresente: ["vuelva", "vuelvas", "vuelva", "volvamos", "volváis", "vuelvan"],
    futuroStem: "volver",
  },
  {
    id: "dormir",
    infinitive: "dormir",
    meaning: "眠る",
    kind: "irregular",
    participio: "dormido",
    presente: ["duermo", "duermes", "duerme", "dormimos", "dormís", "duermen"],
    pretéritoIndefinido: ["dormí", "dormiste", "durmió", "dormimos", "dormisteis", "durmieron"],
    subjuntivoPresente: ["duerma", "duermas", "duerma", "durmamos", "durmáis", "duerman"],
    futuroStem: "dormir",
  },
  {
    id: "sentir",
    infinitive: "sentir",
    meaning: "感じる",
    kind: "irregular",
    participio: "sentido",
    presente: ["siento", "sientes", "siente", "sentimos", "sentís", "sienten"],
    pretéritoIndefinido: ["sentí", "sentiste", "sintió", "sentimos", "sentisteis", "sintieron"],
    subjuntivoPresente: ["sienta", "sientas", "sienta", "sintamos", "sintáis", "sientan"],
    futuroStem: "sentir",
  },
  {
    id: "pedir",
    infinitive: "pedir",
    meaning: "頼む、注文する",
    kind: "irregular",
    participio: "pedido",
    presente: ["pido", "pides", "pide", "pedimos", "pedís", "piden"],
    pretéritoIndefinido: ["pedí", "pediste", "pidió", "pedimos", "pedisteis", "pidieron"],
    subjuntivoPresente: ["pida", "pidas", "pida", "pidamos", "pidáis", "pidan"],
    futuroStem: "pedir",
  },
  {
    id: "seguir",
    infinitive: "seguir",
    meaning: "続ける、ついていく",
    kind: "irregular",
    participio: "seguido",
    presente: ["sigo", "sigues", "sigue", "seguimos", "seguís", "siguen"],
    pretéritoIndefinido: ["seguí", "seguiste", "siguió", "seguimos", "seguisteis", "siguieron"],
    subjuntivoPresente: ["siga", "sigas", "siga", "sigamos", "sigáis", "sigan"],
    futuroStem: "seguir",
  },
  {
    id: "jugar",
    infinitive: "jugar",
    meaning: "遊ぶ、（スポーツを）する",
    kind: "irregular",
    participio: "jugado",
    presente: ["juego", "juegas", "juega", "jugamos", "jugáis", "juegan"],
    pretéritoIndefinido: ["jugué", "jugaste", "jugó", "jugamos", "jugasteis", "jugaron"],
    subjuntivoPresente: ["juegue", "juegues", "juegue", "juguemos", "juguéis", "jueguen"],
    futuroStem: "jugar",
  },
  {
    id: "empezar",
    infinitive: "empezar",
    meaning: "始める",
    kind: "irregular",
    participio: "empezado",
    presente: ["empiezo", "empiezas", "empieza", "empezamos", "empezáis", "empiezan"],
    pretéritoIndefinido: ["empecé", "empezaste", "empezó", "empezamos", "empezasteis", "empezaron"],
    subjuntivoPresente: ["empiece", "empieces", "empiece", "empecemos", "empecéis", "empiecen"],
    futuroStem: "empezar",
  },
  {
    id: "encontrar",
    infinitive: "encontrar",
    meaning: "見つける",
    kind: "irregular",
    participio: "encontrado",
    presente: ["encuentro", "encuentras", "encuentra", "encontramos", "encontráis", "encuentran"],
    pretéritoIndefinido: ["encontré", "encontraste", "encontró", "encontramos", "encontrasteis", "encontraron"],
    subjuntivoPresente: ["encuentre", "encuentres", "encuentre", "encontremos", "encontréis", "encuentren"],
    futuroStem: "encontrar",
  },
  {
    id: "cerrar",
    infinitive: "cerrar",
    meaning: "閉める",
    kind: "irregular",
    participio: "cerrado",
    presente: ["cierro", "cierras", "cierra", "cerramos", "cerráis", "cierran"],
    pretéritoIndefinido: ["cerré", "cerraste", "cerró", "cerramos", "cerrasteis", "cerraron"],
    subjuntivoPresente: ["cierre", "cierres", "cierre", "cerremos", "cerréis", "cierren"],
    futuroStem: "cerrar",
  },
  {
    id: "contar",
    infinitive: "contar",
    meaning: "数える、話す",
    kind: "irregular",
    participio: "contado",
    presente: ["cuento", "cuentas", "cuenta", "contamos", "contáis", "cuentan"],
    pretéritoIndefinido: ["conté", "contaste", "contó", "contamos", "contasteis", "contaron"],
    subjuntivoPresente: ["cuente", "cuentes", "cuente", "contemos", "contéis", "cuenten"],
    futuroStem: "contar",
  },
  {
    id: "entender",
    infinitive: "entender",
    meaning: "理解する",
    kind: "irregular",
    participio: "entendido",
    presente: ["entiendo", "entiendes", "entiende", "entendemos", "entendéis", "entienden"],
    pretéritoIndefinido: ["entendí", "entendiste", "entendió", "entendimos", "entendisteis", "entendieron"],
    subjuntivoPresente: ["entienda", "entiendas", "entienda", "entendamos", "entendáis", "entiendan"],
    futuroStem: "entender",
  },
  {
    id: "morir",
    infinitive: "morir",
    meaning: "死ぬ",
    kind: "irregular",
    participio: "muerto",
    presente: ["muero", "mueres", "muere", "morimos", "morís", "mueren"],
    pretéritoIndefinido: ["morí", "moriste", "murió", "morimos", "moristeis", "murieron"],
    subjuntivoPresente: ["muera", "mueras", "muera", "muramos", "muráis", "mueran"],
    futuroStem: "morir",
  },
  {
    id: "escribir",
    infinitive: "escribir",
    meaning: "書く",
    kind: "irregular",
    participio: "escrito",
    presente: ["escribo", "escribes", "escribe", "escribimos", "escribís", "escriben"],
    pretéritoIndefinido: ["escribí", "escribiste", "escribió", "escribimos", "escribisteis", "escribieron"],
    subjuntivoPresente: ["escriba", "escribas", "escriba", "escribamos", "escribáis", "escriban"],
    futuroStem: "escribir",
  },
  {
    id: "abrir",
    infinitive: "abrir",
    meaning: "開ける",
    kind: "irregular",
    participio: "abierto",
    presente: ["abro", "abres", "abre", "abrimos", "abrís", "abren"],
    pretéritoIndefinido: ["abrí", "abriste", "abrió", "abrimos", "abristeis", "abrieron"],
    subjuntivoPresente: ["abra", "abras", "abra", "abramos", "abráis", "abran"],
    futuroStem: "abrir",
  },
  {
    id: "leer",
    infinitive: "leer",
    meaning: "読む",
    kind: "irregular",
    participio: "leído",
    presente: ["leo", "lees", "lee", "leemos", "leéis", "leen"],
    pretéritoIndefinido: ["leí", "leíste", "leyó", "leímos", "leísteis", "leyeron"],
    subjuntivoPresente: ["lea", "leas", "lea", "leamos", "leáis", "lean"],
    futuroStem: "leer",
  },
  {
    id: "construir",
    infinitive: "construir",
    meaning: "建てる",
    kind: "irregular",
    participio: "construido",
    presente: ["construyo", "construyes", "construye", "construimos", "construís", "construyen"],
    pretéritoIndefinido: ["construí", "construiste", "construyó", "construimos", "construisteis", "construyeron"],
    subjuntivoPresente: ["construya", "construyas", "construya", "construyamos", "construyáis", "construyan"],
    futuroStem: "construir",
  },
  {
    id: "elegir",
    infinitive: "elegir",
    meaning: "選ぶ",
    kind: "irregular",
    participio: "elegido",
    presente: ["elijo", "eliges", "elige", "elegimos", "elegís", "eligen"],
    pretéritoIndefinido: ["elegí", "elegiste", "eligió", "elegimos", "elegisteis", "eligieron"],
    subjuntivoPresente: ["elija", "elijas", "elija", "elijamos", "elijáis", "elijan"],
    futuroStem: "elegir",
  },
];

// 規則動詞: 語尾変化のルールだけで活用可能なため、原形とグループのみ保持する
const regularVerbs: VerbEntry[] = [
  { id: "hablar", infinitive: "hablar", meaning: "話す", kind: "regular", group: "ar" },
  { id: "estudiar", infinitive: "estudiar", meaning: "勉強する", kind: "regular", group: "ar" },
  { id: "trabajar", infinitive: "trabajar", meaning: "働く", kind: "regular", group: "ar" },
  { id: "comer", infinitive: "comer", meaning: "食べる", kind: "regular", group: "er" },
  { id: "beber", infinitive: "beber", meaning: "飲む", kind: "regular", group: "er" },
  { id: "aprender", infinitive: "aprender", meaning: "学ぶ", kind: "regular", group: "er" },
  { id: "vivir", infinitive: "vivir", meaning: "住む、生きる", kind: "regular", group: "ir" },
  { id: "subir", infinitive: "subir", meaning: "登る、上がる", kind: "regular", group: "ir" },
  { id: "recibir", infinitive: "recibir", meaning: "受け取る", kind: "regular", group: "ir" },
];

export const verbs: VerbEntry[] = [...irregularVerbs, ...regularVerbs];
