export interface CharacterCompare {
  id: string;
  japanese: string;
  simplified: string;
  pinyin: string;
  reading: string;
  meaning: string;
  difference: string; // 追加: 漢字の違いを説明する一文
}

export const compareList: CharacterCompare[] = [
  {
    id: "hua",
    japanese: "話",
    simplified: "话",
    pinyin: "huà",
    reading: "わ",
    meaning: "話す",
    difference: "「言」が「讠」という簡略化された部首になっています。",
  },
  {
    id: "shu",
    japanese: "書",
    simplified: "书",
    pinyin: "shū",
    reading: "しょ",
    meaning: "本",
    difference: "上部の「聿」の形が省略され、全体がシンプルな線に置き換わっています。",
  },
  {
    id: "ai",
    japanese: "愛",
    simplified: "爱",
    pinyin: "ài",
    reading: "あい",
    meaning: "愛する",
    difference: "中央の「心」の部分が省略され、代わりに「友」の形が使われています。",
  },
  {
    id: "che",
    japanese: "車",
    simplified: "车",
    pinyin: "chē",
    reading: "しゃ",
    meaning: "車",
    difference: "車輪や車軸を表す線が大幅に省略され、シンプルな形になっています。",
  },
  {
    id: "ma",
    japanese: "馬",
    simplified: "马",
    pinyin: "mǎ",
    reading: "ば",
    meaning: "馬",
    difference: "たてがみや脚を表す部分が省略され、輪郭だけの形になっています。",
  },
  {
    id: "niao",
    japanese: "鳥",
    simplified: "鸟",
    pinyin: "niǎo",
    reading: "ちょう",
    meaning: "鳥",
    difference: "羽や尾を表す線が省略され、シンプルな形になっています。",
  },
  {
    id: "dong",
    japanese: "東",
    simplified: "东",
    pinyin: "dōng",
    reading: "とう",
    meaning: "東",
    difference: "「木」と「日」を組み合わせた形が、省略されたシンプルな形になっています。",
  },
  {
    id: "guang",
    japanese: "広",
    simplified: "广",
    pinyin: "guǎng",
    reading: "こう",
    meaning: "広い",
    difference: "内側の「黄」の部分が省略され、部首の「广」だけが残った形です。",
  },
  {
    id: "ye",
    japanese: "業",
    simplified: "业",
    pinyin: "yè",
    reading: "ぎょう",
    meaning: "仕事・業",
    difference: "上部の複雑な形が省略され、シンプルな線の組み合わせになっています。",
  },
  {
    id: "tie",
    japanese: "鉄",
    simplified: "铁",
    pinyin: "tiě",
    reading: "てつ",
    meaning: "鉄",
    difference: "右側の「失」の部分は同じですが、「金」へんの書き方がやや簡略化されています。",
  },
  {
    id: "yin",
    japanese: "銀",
    simplified: "银",
    pinyin: "yín",
    reading: "ぎん",
    meaning: "銀",
    difference: "右側の「艮」の部分は同じですが、「金」へんの書き方がやや簡略化されています。",
  },
  {
    id: "yi",
    japanese: "医",
    simplified: "医",
    pinyin: "yī",
    reading: "い",
    meaning: "医者・医学",
    difference: "内部の「矢」の部分がやや簡略化されています(ほぼ同じ形です)。",
  },
  {
    id: "hui",
    japanese: "会",
    simplified: "会",
    pinyin: "huì",
    reading: "かい",
    meaning: "会う・会",
    difference: "下部の形がやや異なりますが、全体の構造はほぼ同じです。",
  },
  {
    id: "shi",
    japanese: "実",
    simplified: "实",
    pinyin: "shí",
    reading: "じつ",
    meaning: "実・本当",
    difference: "「宀(うかんむり)」の下の部分が省略され、シンプルな形になっています。",
  },
  {
    id: "zhi",
    japanese: "紙",
    simplified: "纸",
    pinyin: "zhǐ",
    reading: "し",
    meaning: "紙",
    difference: "「糸」へんが「纟」という簡略化された部首になっています。",
  },
  {
    id: "yuan",
    japanese: "園",
    simplified: "园",
    pinyin: "yuán",
    reading: "えん",
    meaning: "庭・園",
    difference: "「囗」の中の「袁」の部分が省略され、「元」だけが残った形です。",
  },
    {
    id: "guan",
    japanese: "関",
    simplified: "关",
    pinyin: "guān",
    reading: "かん",
    meaning: "関係する・閉める",
    difference:
      "「門」の中に「关」が入っている構造から、門構えが完全になくなり、大きく形が変わっています。",
  },
  {
    id: "ti",
    japanese: "體(体)",
    simplified: "体",
    pinyin: "tǐ",
    reading: "たい",
    meaning: "体",
    difference:
      "日本語の新字体「体」とほぼ同じですが、元の繁体字「體」からは大幅に簡略化されています。",
  },
  {
    id: "xian",
    japanese: "線",
    simplified: "线",
    pinyin: "xiàn",
    reading: "せん",
    meaning: "線",
    difference:
      "右側の「泉」の部分が「戋」という別の形に置き換わっており、見た目の印象が大きく変わります。",
  },
  {
    id: "ti2",
    japanese: "題",
    simplified: "题",
    pinyin: "tí",
    reading: "だい",
    meaning: "テーマ・問題",
    difference:
      "左側の「是」の部分は同じですが、右側の「頁」が「页」に簡略化されています。",
  },
  {
    id: "yan",
    japanese: "験",
    simplified: "验",
    pinyin: "yàn",
    reading: "けん",
    meaning: "試す・経験",
    difference:
      "「馬」へんが「马」に簡略化され、右側の形もやや変化しています。",
  },
  {
    id: "yi2",
    japanese: "義",
    simplified: "义",
    pinyin: "yì",
    reading: "ぎ",
    meaning: "意義・正義",
    difference:
      "「羊」と「我」を組み合わせた複雑な形が、点と払いだけのシンプルな形に大幅に簡略化されています。",
  },
  {
    id: "wei",
    japanese: "為",
    simplified: "为",
    pinyin: "wéi",
    reading: "い",
    meaning: "〜のために・行う",
    difference:
      "元の形の面影がほとんど残らないほど、大きく簡略化された代表的な例の一つです。",
  },
  {
    id: "jian",
    japanese: "見",
    simplified: "见",
    pinyin: "jiàn",
    reading: "けん",
    meaning: "見る",
    difference:
      "上部の「目」の形が省略され、シンプルな形に変わっています(見た目は近いですが要注意です)。",
  },
];